---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open-aria.configMapName" . }}
  namespace: {{ .Values.namespace }}
data:
  consumer.properties: {{ .Values.configuration.kafka.consumer.properties | quote }}
  producer.properties: {{ .Values.configuration.kafka.producer.properties | quote }}
  partitions.txt: {{ .Values.configuration.partitions.mapping | quote }}
  aria.yaml: |
    {{- include "ariaConfigTemplate" . | nindent 4 }}
